classDiagram
    class User {
        +user_id: str
        +user_name: str
        +email: str 
        +projects: list[MusicalProject]
        +create_project(title: string) MusicalProject
        +projects_by_genre() Dict~string, int~
        +count_total_projects() int
        +most_used_instrument() VirtualInstrument
    }

    class MusicalProject {
        +project_id: str
        +project_title: str
        +creation_date: date
        +musical_genre: str
        +tracks: list[AudioTrack]
        +add_track(track_name: str): AudioTrack
        +percentage_tracks_with_effects(): float
        +most_used_effect(): EffectType
    }

    class AudioTrack {
        +track_id: str
        +track_name: str
        +duration_seconds: float
        +volume_db: int
        +manual_note_sequence: str
        +used_instrument: VirtualInstrument
        +applied_effects: list[AudioEffect]
        +add_instrument(instrument: VirtualInstrument): None
        +apply_effect(effect: AudioEffect): None
        +remove_effect(effect: AudioEffect): None
        +set_note_sequence(notes: str): None
        +adjust_volume(new_volume_db: int): None
        +has_effects(): bool
        +note_count(): int
    }

    class VirtualInstrument {
        +instrument_id: str
        +instrument_name: str
        +virtual_instrument_type: InstrumentType
        +play_note(note: str, duration: float): None
    }

    class AudioEffect {
        +effect_id: str
        +effect_name: str
        +audio_effect_type: EffectType
    }

    class InstrumentType {
        <<enumeration>>
        DRUMS
        GUITAR
        BASS
    }

    class EffectType {
        <<enumeration>>
        REVERB
        DELAY
        DISTORTION
    }

User "1" -- "0..*" MusicalProject : owns
MusicalProject "1" -- "0..*" AudioTrack : contains
AudioTrack "1" -- "1" VirtualInstrument : uses
AudioTrack "1" -- "0..*" AudioEffect : applies
VirtualInstrument --> InstrumentType
AudioEffect --> EffectType