classDiagram
    class User {
        +user_id: str
        +user_name: str
        +email: str
        +projects: list[MusicProject]
        +MusicProject: create_project(title: str)
    }

    class MusicProject {
        +project_id: str
        +project_title: str
        +creation_date: date
        +music_genre: str
        +tracks: list[AudioTrack]
        +AudioTrack: add_track(track_name: str)
    }

    class AudioTrack {
        +track_id: str
        +track_name: str
        +duration_seconds: float
        +volume_db: int
        +manual_note_sequence: str
        +used_instrument: VirtualInstrument
        +applied_effects: list[AudioEffect]
        +add_instrument(instrument: VirtualInstrument): None
        +apply_effect(effect: AudioEffect): None
        +remove_effect(effect: AudioEffect): None
        +set_note_sequence(notes: string): None
        +adjust_volume(new_volume_db: int): None
    }

    class VirtualInstrument {
        +instrument_id: str
        +instrument_name: str
        +virtual_instrument_type: InstrumentType
        +play_note(note: string, duration: float): None
    }

    class AudioEffect {
        +effect_id: str
        +effect_name: str
        +audio_effect_type: EffectType
    }

    class InstrumentType {
        <<enumeration>>
        DRUMS
        GUITAR
        BASS
    }

    class EffectType {
        <<enumeration>>
        REVERB
        DELAY
        DISTORTION
    }

    User "1" -- "0..*" MusicProject : owns
    MusicProject "1" -- "0..*" AudioTrack : contains
    AudioTrack "1" -- "0..1" VirtualInstrument : uses
    AudioTrack "1" -- "0..*" AudioEffect : applies
    VirtualInstrument --> InstrumentType
    AudioEffect --> EffectType