classDiagram
    class User {
        +user_id: str
        +user_name
        +email
        +List~MusicalProject~ projects
        +create_project(title: string) MusicalProject
        +projects_by_genre() Dict~string, int~
        +count_total_projects() int
        +most_used_instrument() VirtualInstrument
    }

    class MusicalProject {
        +string project_id
        +string project_title
        +date creation_date
        +string musical_genre
        +List~AudioTrack~ tracks
        +add_track(track_name: string) AudioTrack
        +percentage_tracks_with_effects() float
        +most_used_effect() EffectType
    }

    class AudioTrack {
        +string track_id
        +string track_name
        +float duration_seconds
        +int volume_db
        +string manual_note_sequence
        +VirtualInstrument used_instrument
        +List~AudioEffect~ applied_effects
        +add_instrument(instrument: VirtualInstrument) None
        +apply_effect(effect: AudioEffect) None
        +remove_effect(effect: AudioEffect) None
        +set_note_sequence(notes: string) None
        +adjust_volume(new_volume_db: int) None
        +has_effects() bool
        +note_count() int
    }

    class VirtualInstrument {
        +string instrument_id
        +string instrument_name
        +InstrumentType virtual_instrument_type
        +play_note(note: string, duration: float) None
    }

    class AudioEffect {
        +string effect_id
        +string effect_name
        +EffectType audio_effect_type
    }

    class InstrumentType {
        <<enumeration>>
        DRUMS
        GUITAR
        BASS
    }

    class EffectType {
        <<enumeration>>
        REVERB
        DELAY
        DISTORTION
    }

    User "1" -- "0..*" MusicalProject : owns
    MusicalProject "1" -- "0..*" AudioTrack : contains
    AudioTrack "1" -- "1" VirtualInstrument : uses
    AudioTrack "1" -- "0..*" AudioEffect : applies

    VirtualInstrument --> InstrumentType
    AudioEffect --> EffectType