@startuml
class Fraction {
    +numerator: int
    +denominator: int
    __
    +__init__(self, numerator: int, denominator: int)
    +simplify() : void
    +__add__(other: Fraction) : Fraction
    +__sub__(other: Fraction) : Fraction
    +__mul__(other: Fraction) : Fraction
    +__str__() : str
}
@enduml