@startuml
Class Calculator {
    +number1 : int
    +number2 : int
    __
    + {static} __init__(self, number1: int, number2: int)
    + {static} addition() : int
    + {static} subtraction() : int
    + {static} multiplication() : int
    + {static} division() : float
}
@enduml