@startuml
class Libro {
    - title: str
    - uthor: str
    - pages: int
    __
    + __init__(self, title: str, author: str, pages: int)
    + get_title()
    + set_title(title: str)
    + get_author()
    + set_author(author: str)
    + get_pages()
    + set_pages(pages: int)
}

@enduml