@startuml
class Student {
    - name: str
    - freshman: str
    __
    + __init__(self, name: str, freshman: str)
    + get_name(): str
    + set_name(name: str): void
    + get_freshman(): str
    + set_freshman(freshman: str): void
    + add_course(course: Course): void
    + get_courses(): List<Course>
}

class Course {
    - title: str
    - code: str
    __
    + __init__(self, title: str, code: int)
    + get_title(): str
    + set_title(code: int): void
    + get_code(): str
    + set_code(code: int): void
    + add_student(student: Student): void
    + get_students(): List<Student>
}

Student "0..*" -- "0..*" Course
@enduml