@startuml
class Employee {
    +name : str
    +salary : int
    __
    +__init__(self, name : str, salary : int)
    +get_name()
    +set_name(name : str)
    +get_salary()
    +set_salary(salary : int)
}

class Manager {
    +number_of_teams : int
    __
    +__init__(self, name : str, salary : int, number_of_teams : int)
    +super().__init__(name, salary)
    +get_number_of_teams()
    +set_number_of_teams(number_of_teams : int)
}

class Developer {
    +programming_language : str
    __
    +__init__(self, name : str, salary : int, programming_language : str)
    +super().__init__(name, salary)
    +get_programming_language()
    +set_programming_language(programming_language : str)
}

Employee <|-- Manager
Employee <|-- Developer
@enduml